### PR TITLE
Goodbye require

### PR DESCRIPTION
**Pull request by sidvishnoi**
Depends on https://github.com/sidvishnoi/respec-xref-route/pull/45, https://github.com/sidvishnoi/respec-caniuse-route/pull/5

### CODE REVIEW

**Comment by sidvishnoi** [comment]
GitHub action for xref-route and caniuse-route didn't run `prepare` script, and didn't stop release. Got two packages without any actual files on npm 😂
https://unpkg.com/browse/respec-xref-route@6.0.0/
https://unpkg.com/browse/respec-xref-route@6.0.1/

**Comment by marcoscaceres** [comment]
Heh, thankfully it’s only us that depend on them.

**Comment by sidvishnoi** [comment]
Works fine locally. Might need to update server pm2 config (run node with `--experimental-modules`).

**Comment by marcoscaceres** [comment]
Do we need to update node on the server?

**Comment by sidvishnoi** [comment]
Oh yes. Need to update node. ESM comes with v12.
Also, set an env var `DATA_DIR` to point to absolute data directory (`/home/foo/bar/respec.org/data/`)

**Comment by sidvishnoi** [comment]
Lets do the release tomorrow when we have less traffic.

**Comment by marcoscaceres** [comment]
Sounds good. Ping me in the “morning” ;)

**Comment by sidvishnoi** [comment]
Not quite ready for ESM yet..

**Pull request closed without merging**
